Controllers/PredbiljezbaController.cs
using Seminarski_rad_Olujic_AnaMaria.Models;
using Seminarski_rad_Olujic_AnaMaria.Services;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Seminarski_rad_Olujic_AnaMaria.Controllers
{
    [Authorize]
    public class PredbiljezbaController : Controller
    {

        #region General- instanciranje DbService class

        private readonly DbService dbServis;
        public PredbiljezbaController()
        {
            this.dbServis = new DbService();
        }
        #endregion

        #region Predbiljezbe
        
        public ActionResult KreirajPredbiljezbu(int id)
        {
            var seminar = dbServis.DohvatiSeminare().FirstOrDefault(x => x.Id == id);
            ViewBag.Naziv = seminar.Naziv;
            return View();
        }

        [HttpPost]
        public ActionResult KreirajPredbiljezbu(PredbiljezbaModel predbiljezba,int id )
        {
            var seminar = dbServis.DohvatiSeminare().FirstOrDefault(x => x.Id == id);
            predbiljezba.Seminar = seminar;
            predbiljezba.Datum = DateTime.Now;
            predbiljezba.Statusi = Status.Neobrađeno;
            dbServis.KreirajPredbiljezbu(predbiljezba);
            return RedirectToAction("PopisSeminaraZaPredbiljezbu", "Seminar");
        }


        //get: popis predbiljezbi
        //search: naziv, ime, prezime polaznika
        //filter: datum, status
        //sort: naziv, datum, status,
        public ActionResult PopisPredbiljezbi(string searchString, string predbiljezbaStatus, DateTime? searchDate, string sortOrder)
        {

            var predbiljezbe = dbServis.DohvatiPredbiljezbe();

            ViewBag.SortNaziv = sortOrder == "naziv_asc" ? "naziv_desc" : "naziv_asc";
            ViewBag.SortDatum = sortOrder == "datum_asc" ? "datum_desc" : "datum_asc";
            ViewBag.SortStatus = sortOrder == "status_asc" ? "status_desc" : "status_asc";

            if (!String.IsNullOrEmpty(searchString))
            {
                predbiljezbe = predbiljezbe.Where(s => s.Seminar.Naziv.Contains(searchString)
                || s.Ime.Contains(searchString)
                || s.Prezime.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "naziv_desc":
                    predbiljezbe = predbiljezbe.OrderByDescending(s => s.Seminar.Naziv);
                    break;
                case "naziv_asc":
                    predbiljezbe = predbiljezbe.OrderBy(s => s.Seminar.Naziv);
                    break;
                case "datum_desc":
                    predbiljezbe = predbiljezbe.OrderByDescending(x => x.Datum);
                    break;
                case "datum_asc":
                    predbiljezbe = predbiljezbe.OrderBy(s => s.Datum);
                    break;
                case "status_desc":
                    predbiljezbe = predbiljezbe.OrderByDescending(x => x.Statusi);
                    break;
                case "status_asc":
                    predbiljezbe = predbiljezbe.OrderBy(s => s.Statusi);
                    break;
                default:
                    break;
            }

            if (searchDate.HasValue)
            {
                predbiljezbe = predbiljezbe.Where(d => DbFunctions.TruncateTime(d.Datum) == searchDate);
            }

            if (!String.IsNullOrEmpty(predbiljezbaStatus))
            {
                switch (predbiljezbaStatus)
                {
                    case ("Prihvaceno"):
                        predbiljezbe = predbiljezbe.Where(x => x.Statusi == Status.Prihvacen);
                        break;
                    case ("Odbijeno"):
                        predbiljezbe = predbiljezbe.Where(x => x.Statusi == Status.Odbijen);
                        break;
                    case ("Neobradeno"):
                        predbiljezbe = predbiljezbe.Where(x => x.Statusi == Status.Neobrađeno);
                        break;
                    default:
                        break;
                }
            }
            return View("Predbiljezbe", predbiljezbe.ToList());
        }

        public ActionResult UrediPredbiljezbu(int id)
        {
            var predbiljezba = dbServis.DohvatiPredbiljezbe().FirstOrDefault(x => x.Id == id);
            if (predbiljezba == null)
            {
                return RedirectToAction("PopisPredbiljezbi");
            }
            return View(predbiljezba);
        }

        [HttpPost]
        public ActionResult UrediPredbiljezbu(PredbiljezbaModel predbiljezba)
        {
            dbServis.UrediPredbiljezbu(predbiljezba);
            return RedirectToAction("PopisPredbiljezbi");

        }

        #endregion


    }
}

Views/Predbiljezba/KreirajPredbiljezbu.cshtml
@model Seminarski_rad_Olujic_AnaMaria.Models.PredbiljezbaModel

@{
    ViewBag.Title = "Nova predbilježba";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .control-label{
        width: 10%;
    }
    .form-horizontal .control-label {
        text-align: left;
    }
</style>




@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <br />
    <div class="form-horizontal">
        <p>Molimo unesite osobne podatke za predbilježbu na seminar.</p>
        <h3>@ViewBag.Naziv</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Odustani" class="btn btn-danger" onclick="window.location.href ='@Url.Action("PopisSeminaraZaPredbiljezbu", "Seminar")'" ; />
                <input type="submit" value="Predbilježi se" class="btn btn-primary" />
            </div>
            
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Predbiljezba/Predbiljezbe.cshtml
@model IEnumerable<Seminarski_rad_Olujic_AnaMaria.Models.PredbiljezbaModel>

@{
    ViewBag.Title = "PopisPredbiljezbi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<p>
    @using (Html.BeginForm("PopisPredbiljezbi", "Predbiljezba", null, FormMethod.Get, new { @class = "form-inline" }))
    {

    <div class="container">
        <div class="row">
            <div class="form-group col-sd-3">
                <label>Status:</label>
            </div>
            <div class="form-group col-sd-3">
                <select name="predbiljezbaStatus" class="form-control">
                    <option value="Sve">Sve</option>
                    <option value="Prihvaceno">Prihvćeno</option>
                    <option value="Odbijeno">Odbijeno</option>
                    <option value="Neobradeno">Neobrađeno</option>
                </select>
            </div>

            @Html.Partial("_Search")
        </div>
        
    </div>
     

    }

</p>

<br />


<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.ActionLink("Seminar", "PopisPredbiljezbi", new { sortOrder = ViewBag.SortNaziv })
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prezime)
            </th>
            <th>
                @Html.ActionLink("Datum", "PopisPredbiljezbi", new { sortOrder = ViewBag.SortDatum })
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Adresa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefon)
            </th>
            <th>
                @Html.ActionLink("Status", "PopisPredbiljezbi", new { sortOrder = ViewBag.SortStatus })
            </th>
        </tr>

    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink("Odaberi", "UrediPredbiljezbu", new { id = item.Id })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Seminar.Naziv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prezime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Datum)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Adresa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Telefon)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Statusi)
                </td>

            </tr>
        }
    </tbody>

</table>

Views/Predbiljezba/UrediPredbiljezbu.cshtml
@model Seminarski_rad_Olujic_AnaMaria.Models.PredbiljezbaModel

@{
    ViewBag.Title = "UrediPredbiljezbu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<style>
    .control-label {
        width: 10%;
    }

    .form-horizontal .control-label {
        text-align: left;
    }

</style>




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Seminar.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Seminar.Naziv, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Datum, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(model=>model.Datum)

    <div class="form-group">
        @Html.LabelFor(model => model.Datum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Datum, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Datum, "", new { @class = "text-danger" })
        </div>
    </div>

    

    <div class="form-group">
        @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Adresa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Adresa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Adresa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefon, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Statusi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.RadioButtonFor(x=>x.Statusi, "Prihvacen") @Html.Label("Prihvaćen")
            @Html.RadioButtonFor(x=>x.Statusi, "Odbijen") @Html.Label("Odbijen")
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            @Html.ActionLink("Odbaci", "PopisPredbiljezbi", null, new { @class = "btn btn-danger" })
            <input type="submit" value="Spremi" class="btn btn-primary" />
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}